version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=renan
      - POSTGRESQL_PASSWORD=renan
      - POSTGRESQL_DATABASE=api-gemini